version: "3.8"

services:
  frontend:
    build: ./Frontend/imposter-socket
    # Produces a static build, not served directly
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_SOCKET_URL=/
      - SERVER_WEB_SOCKET_PATH=/socket.io

  backend:
    build: ./Backend/imposter_server
    expose:
      - 4000
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "3105:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Frontend/imposter-socket/out:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
