version: "3.8"

services:
  frontend:
    build: ./Frontend/imposter-socket
    networks:
      - app-network

  backend:
    build: ./Backend/imposter_server
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "3105:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
