name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend/imposter-socket
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ vars.DOCKER_USERNAME }}/imposter-game:frontend

      - name: Build and push backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./Backend/imposter_server
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ vars.DOCKER_USERNAME }}/imposter-game:backend

      - name: Build and push nginx reverse proxy Image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ vars.DOCKER_USERNAME }}/imposter-game:reverse-proxy
